### PR TITLE
feat: add keyboard controls to replicate button behavior

### PR DESCRIPTION
**Pull request by Ssentiago**
- Implement Arrow key events to move the diagram
- Implement =/+ and - keys for zooming the diagram
- Implement 0 key to reset diagram zoom and position
- Add optional conditional animations for moving and zooming the diagram

--- 
Is animation necessary? I tested it and found that it looks blurry. I haven't discovered an effective way to resolve this issue yet.
I've also noticed a potential bug: keyboard events stop working when entering fullscreen mode for the container. This might be because the container loses focus.

### CODE REVIEW

**Comment by gitcpy** [comment]
It is up to you. Although it is a trend to make actions in animation, there is not always a good way to implement.
If you find it easy to make it yourself, do it, or let it.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月14日(星期六) 上午6:44
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[gitcpy/mermaid-zoom-drag] feat: add keyboard controls to replicate button behavior (PR #10)



 
Implement Arrow key events to move the diagram
 
Implement =/+ and - keys for zooming the diagram
 
Implement 0 key to reset diagram zoom and position
 
Add optional conditional animations for moving and zooming the diagram
  
 
Is animation necessary? I tested it and found that it looks blurry. I haven't discovered an effective way to resolve this issue yet.
 
 
You can view, comment on, or merge this pull request online at:
 
&nbsp; https://github.com/gitcpy/mermaid-zoom-drag/pull/10
 
Commit Summary
    
eacc619  feat: add keyboard controls to replicate button behavior
  
File Changes 
 
(1 file)
    
     M     src/main.ts     (122)   
  
Patch Links:
    
https://github.com/gitcpy/mermaid-zoom-drag/pull/10.patch
   
https://github.com/gitcpy/mermaid-zoom-drag/pull/10.diff

**Comment by Ssentiago** [comment]
> It is up to you. Although it is a trend to make actions in animation, there is not always a good way to implement.
> If you find it easy to make it yourself, do it, or let it.&nbsp;
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2024年9月14日(星期六) 上午6:44
> ***@***.***&gt;;
> ***@***.***&gt;;
> 主题:&nbsp;[gitcpy/mermaid-zoom-drag] feat: add keyboard controls to replicate button behavior (PR #10)
> 
> 
> 
>  
> Implement Arrow key events to move the diagram
>  
> Implement =/+ and - keys for zooming the diagram
>  
> Implement 0 key to reset diagram zoom and position
>  
> Add optional conditional animations for moving and zooming the diagram
>   
>  
> Is animation necessary? I tested it and found that it looks blurry. I haven't discovered an effective way to resolve this issue yet.
>  
>  
> You can view, comment on, or merge this pull request online at:
>  
> &nbsp; https://github.com/gitcpy/mermaid-zoom-drag/pull/10
>  
> Commit Summary
>     
> eacc619  feat: add keyboard controls to replicate button behavior
>   
> File Changes 
>  
> (1 file)
>     
>      M     src/main.ts     (122)   
>   
> Patch Links:
>     
> https://github.com/gitcpy/mermaid-zoom-drag/pull/10.patch
>    
> https://github.com/gitcpy/mermaid-zoom-drag/pull/10.diff
>   
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

Please take a look at this branch as soon as you have time. Are the things I mentioned critical for you?

**Comment by gitcpy** [comment]
OK! Check it now




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月14日(星期六) 中午11:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gitcpy/mermaid-zoom-drag] feat: add keyboard controls to replicate button behavior (PR #10)





  
It is up to you. Although it is a trend to make actions in animation, there is not always a good way to implement.
 If you find it easy to make it yourself, do it, or let it.&nbsp;
 
------------------&nbsp;原始邮件&nbsp;------------------
 发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    @.&gt;;
 发送时间:&nbsp;2024年9月14日(星期六) 上午6:44
 @.&gt;;
 @.***&gt;;
 主题:&nbsp;[gitcpy/mermaid-zoom-drag] feat: add keyboard controls to replicate button behavior (PR #10)
 
Implement Arrow key events to move the diagram
 
Implement =/+ and - keys for zooming the diagram
 
Implement 0 key to reset diagram zoom and position
 
Add optional conditional animations for moving and zooming the diagram
 
Is animation necessary? I tested it and found that it looks blurry. I haven't discovered an effective way to resolve this issue yet.
 
You can view, comment on, or merge this pull request online at:
 
&nbsp; #10
 
Commit Summary
 
eacc619  feat: add keyboard controls to replicate button behavior
 
File Changes
 
(1 file)
  M     src/main.ts     (122)     
Patch Links:
 
https://github.com/gitcpy/mermaid-zoom-drag/pull/10.patch
 
https://github.com/gitcpy/mermaid-zoom-drag/pull/10.diff
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you are subscribed to this thread.Message ID: @.***&gt;
  
Please take a look at this branch as soon as you have time. Are the things I mentioned critical for you?

**Comment by gitcpy** [comment]
I am sorry there is an error reported.&nbsp;
What should I do to solve it?
Here is the info:
Plugin failure: mermaid-zoom-drag Error: Cannot find module './constants'
Require stack:
- electron/js2c/renderer_init
&nbsp; &nbsp; at Module._resolveFilename (node:internal/modules/cjs/loader:1152:15)
&nbsp; &nbsp; at a._resolveFilename (node:electron/js2c/renderer_init:2:2669)
&nbsp; &nbsp; at Module._load (node:internal/modules/cjs/loader:993:27)
&nbsp; &nbsp; at c._load (node:electron/js2c/node_init:2:13801)
&nbsp; &nbsp; at s._load (node:electron/js2c/renderer_init:2:31018)
&nbsp; &nbsp; at Module.require (node:internal/modules/cjs/loader:1240:19)
&nbsp; &nbsp; at require (node:internal/modules/helpers:179:18)
&nbsp; &nbsp; at ac (app.js:1:516351)
&nbsp; &nbsp; at a (app.js:1:2292441)
&nbsp; &nbsp; at anonymous (plugin:mermaid-zoom-drag:4:21)
&nbsp; &nbsp; at e.<anonymous&gt; (app.js:1:2292629)
&nbsp; &nbsp; at app.js:1:237138
&nbsp; &nbsp; at Object.next (app.js:1:237243)
&nbsp; &nbsp; at a (app.js:1:235961)



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月14日(星期六) 中午11:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gitcpy/mermaid-zoom-drag] feat: add keyboard controls to replicate button behavior (PR #10)





  
It is up to you. Although it is a trend to make actions in animation, there is not always a good way to implement.
 If you find it easy to make it yourself, do it, or let it.&nbsp;
 
------------------&nbsp;原始邮件&nbsp;------------------
 发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    @.&gt;;
 发送时间:&nbsp;2024年9月14日(星期六) 上午6:44
 @.&gt;;
 @.***&gt;;
 主题:&nbsp;[gitcpy/mermaid-zoom-drag] feat: add keyboard controls to replicate button behavior (PR #10)
 
Implement Arrow key events to move the diagram
 
Implement =/+ and - keys for zooming the diagram
 
Implement 0 key to reset diagram zoom and position
 
Add optional conditional animations for moving and zooming the diagram
 
Is animation necessary? I tested it and found that it looks blurry. I haven't discovered an effective way to resolve this issue yet.
 
You can view, comment on, or merge this pull request online at:
 
&nbsp; #10
 
Commit Summary
 
eacc619  feat: add keyboard controls to replicate button behavior
 
File Changes
 
(1 file)
  M     src/main.ts     (122)     
Patch Links:
 
https://github.com/gitcpy/mermaid-zoom-drag/pull/10.patch
 
https://github.com/gitcpy/mermaid-zoom-drag/pull/10.diff
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you are subscribed to this thread.Message ID: @.***&gt;
  
Please take a look at this branch as soon as you have time. Are the things I mentioned critical for you?

**Comment by Ssentiago** [comment]
> I am sorry there is an error reported.&nbsp;
> What should I do to solve it?
> Here is the info:
> Plugin failure: mermaid-zoom-drag Error: Cannot find module './constants'
> Require stack:
> - electron/js2c/renderer_init
> &nbsp; &nbsp; at Module._resolveFilename (node:internal/modules/cjs/loader:1152:15)
> &nbsp; &nbsp; at a._resolveFilename (node:electron/js2c/renderer_init:2:2669)
> &nbsp; &nbsp; at Module._load (node:internal/modules/cjs/loader:993:27)
> &nbsp; &nbsp; at c._load (node:electron/js2c/node_init:2:13801)
> &nbsp; &nbsp; at s._load (node:electron/js2c/renderer_init:2:31018)
> &nbsp; &nbsp; at Module.require (node:internal/modules/cjs/loader:1240:19)
> &nbsp; &nbsp; at require (node:internal/modules/helpers:179:18)
> &nbsp; &nbsp; at ac (app.js:1:516351)
> &nbsp; &nbsp; at a (app.js:1:2292441)
> &nbsp; &nbsp; at anonymous (plugin:mermaid-zoom-drag:4:21)
> &nbsp; &nbsp; at e.<anonymous&gt; (app.js:1:2292629)
> &nbsp; &nbsp; at app.js:1:237138
> &nbsp; &nbsp; at Object.next (app.js:1:237243)
> &nbsp; &nbsp; at a (app.js:1:235961)
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2024年9月14日(星期六) 中午11:40
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [gitcpy/mermaid-zoom-drag] feat: add keyboard controls to replicate button behavior (PR #10)
> 
> 
> 
> 
> 
>   
> It is up to you. Although it is a trend to make actions in animation, there is not always a good way to implement.
>  If you find it easy to make it yourself, do it, or let it.&nbsp;
>  
> ------------------&nbsp;原始邮件&nbsp;------------------
>  发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    @.&gt;;
>  发送时间:&nbsp;2024年9月14日(星期六) 上午6:44
>  @.&gt;;
>  @.***&gt;;
>  主题:&nbsp;[gitcpy/mermaid-zoom-drag] feat: add keyboard controls to replicate button behavior (PR #10)
>  
> Implement Arrow key events to move the diagram
>  
> Implement =/+ and - keys for zooming the diagram
>  
> Implement 0 key to reset diagram zoom and position
>  
> Add optional conditional animations for moving and zooming the diagram
>  
> Is animation necessary? I tested it and found that it looks blurry. I haven't discovered an effective way to resolve this issue yet.
>  
> You can view, comment on, or merge this pull request online at:
>  
> &nbsp; #10
>  
> Commit Summary
>  
> eacc619  feat: add keyboard controls to replicate button behavior
>  
> File Changes
>  
> (1 file)
>   M     src/main.ts     (122)     
> Patch Links:
>  
> https://github.com/gitcpy/mermaid-zoom-drag/pull/10.patch
>  
> https://github.com/gitcpy/mermaid-zoom-drag/pull/10.diff
>  
> —
>  Reply to this email directly, view it on GitHub, or unsubscribe.
>  You are receiving this because you are subscribed to this thread.Message ID: @.***&gt;
>   
> Please take a look at this branch as soon as you have time. Are the things I mentioned critical for you?
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

Do you use commonjs? Or maybe you didn't update the local repository with a remote one?

**Comment by gitcpy** [comment]
I get codes from the new branch, here is the snapshot.
I am not familiar with “require”.
Please analyse it for me. Thanks.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月14日(星期六) 中午12:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gitcpy/mermaid-zoom-drag] feat: add keyboard controls to replicate button behavior (PR #10)





  
I am sorry there is an error reported.&nbsp;
 What should I do to solve it?
 Here is the info:
 Plugin failure: mermaid-zoom-drag Error: Cannot find module './constants'
 Require stack:
  
electron/js2c/renderer_init
 &nbsp; &nbsp; at Module._resolveFilename (node:internal/modules/cjs/loader:1152:15)
 &nbsp; &nbsp; at a._resolveFilename (node:electron/js2c/renderer_init:2:2669)
 &nbsp; &nbsp; at Module._load (node:internal/modules/cjs/loader:993:27)
 &nbsp; &nbsp; at c._load (node:electron/js2c/node_init:2:13801)
 &nbsp; &nbsp; at s._load (node:electron/js2c/renderer_init:2:31018)
 &nbsp; &nbsp; at Module.require (node:internal/modules/cjs/loader:1240:19)
 &nbsp; &nbsp; at require (node:internal/modules/helpers:179:18)
 &nbsp; &nbsp; at ac (app.js:1:516351)
 &nbsp; &nbsp; at a (app.js:1:2292441)
 &nbsp; &nbsp; at anonymous (plugin:mermaid-zoom-drag:4:21)
 &nbsp; &nbsp; at e.<anonymous&gt; (app.js:1:2292629)
 &nbsp; &nbsp; at app.js:1:237138
 &nbsp; &nbsp; at Object.next (app.js:1:237243)
 &nbsp; &nbsp; at a (app.js:1:235961)
  
------------------&nbsp;原始邮件&nbsp;------------------
 发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    @.&gt;;
 发送时间:&nbsp;2024年9月14日(星期六) 中午11:40
 @.&gt;;
 @.@.&gt;;
 主题:&nbsp;Re: [gitcpy/mermaid-zoom-drag] feat: add keyboard controls to replicate button behavior (PR #10)
 
It is up to you. Although it is a trend to make actions in animation, there is not always a good way to implement.
 If you find it easy to make it yourself, do it, or let it.&nbsp;
 
------------------&nbsp;原始邮件&nbsp;------------------
 发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    @.&gt;;
 发送时间:&nbsp;2024年9月14日(星期六) 上午6:44
 @.&gt;;
 @.***&gt;;
 主题:&nbsp;[gitcpy/mermaid-zoom-drag] feat: add keyboard controls to replicate button behavior (PR #10)
 
Implement Arrow key events to move the diagram
 
Implement =/+ and - keys for zooming the diagram
 
Implement 0 key to reset diagram zoom and position
 
Add optional conditional animations for moving and zooming the diagram
 
Is animation necessary? I tested it and found that it looks blurry. I haven't discovered an effective way to resolve this issue yet.
 
You can view, comment on, or merge this pull request online at:
 
&nbsp; #10
 
Commit Summary
 
eacc619  feat: add keyboard controls to replicate button behavior
 
File Changes
 
(1 file)
 M     src/main.ts     (122)
 Patch Links:
 
https://github.com/gitcpy/mermaid-zoom-drag/pull/10.patch
 
https://github.com/gitcpy/mermaid-zoom-drag/pull/10.diff
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you are subscribed to this thread.Message ID: @.***&gt;
 
Please take a look at this branch as soon as you have time. Are the things I mentioned critical for you?
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you commented.Message ID: @.***&gt;
  
Do you use commonjs? Or maybe you didn't update the local repository with a remote one?

**Comment by Ssentiago** [comment]
> I get codes from the new branch, here is the snapshot.
> I am not familiar with “require”.
> Please analyse it for me. Thanks.
> 
> 
> 
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2024年9月14日(星期六) 中午12:11
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [gitcpy/mermaid-zoom-drag] feat: add keyboard controls to replicate button behavior (PR #10)
> 
> 
> 
> 
> 
>   
> I am sorry there is an error reported.&nbsp;
>  What should I do to solve it?
>  Here is the info:
>  Plugin failure: mermaid-zoom-drag Error: Cannot find module './constants'
>  Require stack:
>   
> electron/js2c/renderer_init
>  &nbsp; &nbsp; at Module._resolveFilename (node:internal/modules/cjs/loader:1152:15)
>  &nbsp; &nbsp; at a._resolveFilename (node:electron/js2c/renderer_init:2:2669)
>  &nbsp; &nbsp; at Module._load (node:internal/modules/cjs/loader:993:27)
>  &nbsp; &nbsp; at c._load (node:electron/js2c/node_init:2:13801)
>  &nbsp; &nbsp; at s._load (node:electron/js2c/renderer_init:2:31018)
>  &nbsp; &nbsp; at Module.require (node:internal/modules/cjs/loader:1240:19)
>  &nbsp; &nbsp; at require (node:internal/modules/helpers:179:18)
>  &nbsp; &nbsp; at ac (app.js:1:516351)
>  &nbsp; &nbsp; at a (app.js:1:2292441)
>  &nbsp; &nbsp; at anonymous (plugin:mermaid-zoom-drag:4:21)
>  &nbsp; &nbsp; at e.<anonymous&gt; (app.js:1:2292629)
>  &nbsp; &nbsp; at app.js:1:237138
>  &nbsp; &nbsp; at Object.next (app.js:1:237243)
>  &nbsp; &nbsp; at a (app.js:1:235961)
>   
> ------------------&nbsp;原始邮件&nbsp;------------------
>  发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    @.&gt;;
>  发送时间:&nbsp;2024年9月14日(星期六) 中午11:40
>  @.&gt;;
>  @.@.&gt;;
>  主题:&nbsp;Re: [gitcpy/mermaid-zoom-drag] feat: add keyboard controls to replicate button behavior (PR #10)
>  
> It is up to you. Although it is a trend to make actions in animation, there is not always a good way to implement.
>  If you find it easy to make it yourself, do it, or let it.&nbsp;
>  
> ------------------&nbsp;原始邮件&nbsp;------------------
>  发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    @.&gt;;
>  发送时间:&nbsp;2024年9月14日(星期六) 上午6:44
>  @.&gt;;
>  @.***&gt;;
>  主题:&nbsp;[gitcpy/mermaid-zoom-drag] feat: add keyboard controls to replicate button behavior (PR #10)
>  
> Implement Arrow key events to move the diagram
>  
> Implement =/+ and - keys for zooming the diagram
>  
> Implement 0 key to reset diagram zoom and position
>  
> Add optional conditional animations for moving and zooming the diagram
>  
> Is animation necessary? I tested it and found that it looks blurry. I haven't discovered an effective way to resolve this issue yet.
>  
> You can view, comment on, or merge this pull request online at:
>  
> &nbsp; #10
>  
> Commit Summary
>  
> eacc619  feat: add keyboard controls to replicate button behavior
>  
> File Changes
>  
> (1 file)
>  M     src/main.ts     (122)
>  Patch Links:
>  
> https://github.com/gitcpy/mermaid-zoom-drag/pull/10.patch
>  
> https://github.com/gitcpy/mermaid-zoom-drag/pull/10.diff
>  
> —
>  Reply to this email directly, view it on GitHub, or unsubscribe.
>  You are receiving this because you are subscribed to this thread.Message ID: @.***&gt;
>  
> Please take a look at this branch as soon as you have time. Are the things I mentioned critical for you?
>  
> —
>  Reply to this email directly, view it on GitHub, or unsubscribe.
>  You are receiving this because you commented.Message ID: @.***&gt;
>   
> Do you use commonjs? Or maybe you didn't update the local repository with a remote one?
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

Have you seen the changes?

**Comment by gitcpy** [comment]
I see changes in code.
And after my buuilding,&nbsp;I try to see the plugin in ob, then the error is reported.
But this is not important, just take a look.
I think you are a pro more than me.
I believe in you for all your decision.&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月14日(星期六) 中午12:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gitcpy/mermaid-zoom-drag] feat: add keyboard controls to replicate button behavior (PR #10)














  
I get codes from the new branch, here is the snapshot.
 I am not familiar with “require”.
 Please analyse it for me. Thanks.
 
------------------&nbsp;原始邮件&nbsp;------------------
 发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    @.&gt;;
 发送时间:&nbsp;2024年9月14日(星期六) 中午12:11
 @.&gt;;
 @.@.&gt;;
 主题:&nbsp;Re: [gitcpy/mermaid-zoom-drag] feat: add keyboard controls to replicate button behavior (PR #10)
 
I am sorry there is an error reported.&nbsp;
 What should I do to solve it?
 Here is the info:
 Plugin failure: mermaid-zoom-drag Error: Cannot find module './constants'
 Require stack:
 
electron/js2c/renderer_init
 &nbsp; &nbsp; at Module._resolveFilename (node:internal/modules/cjs/loader:1152:15)
 &nbsp; &nbsp; at a._resolveFilename (node:electron/js2c/renderer_init:2:2669)
 &nbsp; &nbsp; at Module._load (node:internal/modules/cjs/loader:993:27)
 &nbsp; &nbsp; at c._load (node:electron/js2c/node_init:2:13801)
 &nbsp; &nbsp; at s._load (node:electron/js2c/renderer_init:2:31018)
 &nbsp; &nbsp; at Module.require (node:internal/modules/cjs/loader:1240:19)
 &nbsp; &nbsp; at require (node:internal/modules/helpers:179:18)
 &nbsp; &nbsp; at ac (app.js:1:516351)
 &nbsp; &nbsp; at a (app.js:1:2292441)
 &nbsp; &nbsp; at anonymous (plugin:mermaid-zoom-drag:4:21)
 &nbsp; &nbsp; at e.<anonymous&gt; (app.js:1:2292629)
 &nbsp; &nbsp; at app.js:1:237138
 &nbsp; &nbsp; at Object.next (app.js:1:237243)
 &nbsp; &nbsp; at a (app.js:1:235961)
 
------------------&nbsp;原始邮件&nbsp;------------------
 发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    @.&gt;;
 发送时间:&nbsp;2024年9月14日(星期六) 中午11:40
 @.&gt;;
 @.@.&gt;;
 主题:&nbsp;Re: [gitcpy/mermaid-zoom-drag] feat: add keyboard controls to replicate button behavior (PR #10)
 
It is up to you. Although it is a trend to make actions in animation, there is not always a good way to implement.
 If you find it easy to make it yourself, do it, or let it.&nbsp;
 
------------------&nbsp;原始邮件&nbsp;------------------
 发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    @.&gt;;
 发送时间:&nbsp;2024年9月14日(星期六) 上午6:44
 @.&gt;;
 @.***&gt;;
 主题:&nbsp;[gitcpy/mermaid-zoom-drag] feat: add keyboard controls to replicate button behavior (PR #10)
 
Implement Arrow key events to move the diagram
 
Implement =/+ and - keys for zooming the diagram
 
Implement 0 key to reset diagram zoom and position
 
Add optional conditional animations for moving and zooming the diagram
 
Is animation necessary? I tested it and found that it looks blurry. I haven't discovered an effective way to resolve this issue yet.
 
You can view, comment on, or merge this pull request online at:
 
&nbsp; #10
 
Commit Summary
 
eacc619  feat: add keyboard controls to replicate button behavior
 
File Changes
 
(1 file)
 M     src/main.ts     (122)
 Patch Links:
 
https://github.com/gitcpy/mermaid-zoom-drag/pull/10.patch
 
https://github.com/gitcpy/mermaid-zoom-drag/pull/10.diff
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you are subscribed to this thread.Message ID: @.***&gt;
 
Please take a look at this branch as soon as you have time. Are the things I mentioned critical for you?
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you commented.Message ID: @.***&gt;
 
Do you use commonjs? Or maybe you didn't update the local repository with a remote one?
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you commented.Message ID: @.***&gt;
  
Have you seen the changes?

**Pull request merged**
